# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [26.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm ci

      - name: Restore cover image cache
        id: restore-cover-images
        uses: actions/cache/restore@v6
        with:
          path: .cover-cache
          key: cover-cache

      - run: npm run build

      - name: Save cover image cache
        id: save-cover-images
        uses: actions/cache/save@v6
        with:
          path: .cover-cache
          key: cover-cache

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [26.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run lint

  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [26.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"
  #         cache-dependency-path: package-lock.json
  #     - run: npm ci
  #     - run: npm test
